### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by maplepy** [maxsupermanhd/meteor-constantiam#1]

**Comment by maxsupermanhd** [comment]
This addon implements ultra fast elytrafly but it was patched when constantiam changed anticheat, you earlier could achieve up to 720km/h speeds. Right now it serves no purpose except providing BleachHack's elytra boost to meteor

**Comment by maplepy** [comment]
ooh wow that's impressive! what a bummer :/

thank you for the quick reply bro :)
